name: 'untitled1'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'


#dependencies:
#  my_dependency: any
dependencies:
     path:
     browser: '>=0.10.0 <0.11.0'
     shelf:
     shelf_route:
     sqljocky:
     json_object: any
     json:
     logging: any
dev_dependencies:
       mockito: any
       test: any

